Ukrainian: translate 'Version' and 'Last update'
asciidoc-py/asciidoc-py2 pull request #101
Opened 2016-09-24 20:58 UTC by hedrok

2016-09-24 23:06 UTC, elextr commented on lang-uk.conf
> +Востаннє оновлено
This should have `{docdate} {doctime}` after it.

2016-09-24 23:07 UTC, elextr requested changes

2016-09-25 10:08 UTC, hedrok commented
Are you sure?.. I've checked lang-en, lang-de, lang-fr, none of them has this after various translations of "Last update".
Only lang-pl.conf has "{docdate} {doctime}", all others (including lang-uk) use "template::[footer-date]" which is defined in html4.conf and html5.conf as "{docdate} {doctime}" with some conditions.
Should I change lang-pl?.. I think "template::[footer-date]" is better.
What should I do? :)

2016-09-25 12:24 UTC, elextr commented
@hedrok you are right, the change to remove the attributes was added earlier this year

But the lang-pl was added for the first time two days before the change that removed the attributes, so it was not in that change set. Oh well.  Has been fixed separately.

2016-09-25 12:24 UTC, elextr approved these changes

2016-09-25 12:25 UTC, merged

2016-09-25 12:49 UTC, hedrok commented
Thank you for merging, but see my comment to your changes of lang-pl.conf please